<?php

namespace AffiliateDashboardBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyName($name)
    {
        return $this->findOneByName($name);
    }
}
